[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "elk"
description = "Keeping language models honest by directly eliciting knowledge encoded in their activations"
readme = "README.md"
requires-python = ">=3.9"
keywords = ["nlp", "interpretability", "language-models", "explainable-ai"]
license = {text = "MIT License"}
dependencies = [
    "datasets",
    "matplotlib",
    "numpy",
    "pandas",
    "promptsource",
    "umap-learn",
    "seaborn",
    "scikit-learn",
    "torch",
    "transformers",
]
version = "0.0.1"

[project.optional-dependencies]
dev = [
    "pre-commit",
    "pytest",
]

[tool.setuptools]
packages = ["elk"]
