elk sweep --net.seed 42 \
    --template_path /home/laurito/elk/scripts/templates/personas/train/claims/ \
    --net ccs \
    --norm burns \
    --cluster_algo None \
    --dataset_from_file True \
    --models "mistralai/Mistral-7B-v0.1" \
    --datasets "/home/laurito/elk/datasets/claim" \
    --skip_transfer_eval \
    --num_gpus 1 \
    --disable_cache
